# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo install requirement in pre_build  sections ...
      - ls -lah
  build:
    commands:
      - echo Build started on `date` 
      - echo Installing source NPM dependencies...
      - npm install
      - echo Compiling the app.js code in build stage
      - ls -lah
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build Done by Muhammad Ismaeel Haider
# Include only the files required for your application to run.
artifacts:
  files:
    - app.js
    - package.json
    - node_modules/**/*
